### ISSUE TITLE
Uninitialized Constant Vipergen::FileManager::FileUtils (NameError)

### ISSUE THREAD

**Issue by ahmedomer** [redbooth/viper-module-generator#9]
vipergen generate MyFirstViperModule --path=~/Desktop/

```
------- VIPER GENERATOR---------
generate
MyFirstViperModule
--path=~/Desktop/
Generating VIPER-Module
Template: default
Language: swift
Name: MyFirstViperModule
Path: ~/Desktop/
Author: VIPER
Company: Company
/Library/Ruby/Gems/2.0.0/gems/vipergen-0.2.6/lib/vipergen/filemanager.rb:39:in `copy': uninitialized constant Vipergen::FileManager::FileUtils (NameError)
	from /Library/Ruby/Gems/2.0.0/gems/vipergen-0.2.6/lib/vipergen/generator.rb:22:in `generate_viper'
	from /Library/Ruby/Gems/2.0.0/gems/vipergen-0.2.6/lib/vipergen/viperthor.rb:13:in `generate'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/vipergen-0.2.6/bin/vipergen:8:in `<top (required)>'
	from /usr/local/bin/vipergen:23:in `load'
	from /usr/local/bin/vipergen:23:in `<main>'
```

**Comment by martinogg** [comment]
Any updates on this? mac OS 10.13, Xcode 9.1, gem 2.3

**Comment by timbaev** [comment]
I have this problem too. Any solutions?

**Comment by twof** [comment]
Try this fork maybe?
https://github.com/redbooth/viper-module-generator/pull/7

**Comment by jfmiler** [comment]
@martinogg @timbaev we are in the process of retiring this project and don't intend on maintaining it further. If you are interested in the functionality, a more recent (however still retired) fork of the project is available at https://github.com/pepibumur/viper-module-generator.
